# Generated by Django 6.0.7 on 2026-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the blog post", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="SEO URL slug. Generated automatically if blank.",
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Main content of the blog post"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the skill name (e.g., Python, React)",
                        max_length=100,
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        help_text="Enter proficiency level as percentage (0-100)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Frontend", "Frontend Development"),
                            ("Backend", "Backend Development"),
                            ("Database", "Database Management"),
                            ("Devops", "DevOps & Tools"),
                            ("Soft Skills", "Soft Skills"),
                            ("Other", "Other Tech Stack"),
                        ],
                        default="Frontend",
                        help_text="Select the category for this skill",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["-proficiency"],
            },
        ),
    ]
