# Generated by Django 6.0.7 on 2026-07-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["-percentage"]},
        ),
        migrations.RenameField(
            model_name="skill",
            old_name="proficiency",
            new_name="percentage",
        ),
    ]
